image: docker:latest
services:
- docker:dind

stages:
- build
- release

variables:
  CONTAINER_TEST_IMAGE: $GCR_ENDPOINT/$GCP_PROJECT/ci:$CI_BUILD_REF
  CONTAINER_RELEASE_IMAGE: $GCR_ENDPOINT/$GCP_PROJECT/ci:latest

build:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

release:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master
